language: node_js
node_js:
  - 0.8
  - 0.10
before_script:
  - mysql -e 'create database mysql_dynamo_test;'
  - "npm install -g mocha grunt-cli"

# These are IAM credentials limited to Travis-CI, so don't get any funny ideas wiseguy.
env: MYSQLDYN_TEST_HOST=127.0.0.1 MYSQLDYN_TEST_USER=root MYSQLDYN_TEST_PW="" MYSQLDYN_TEST_DB=mysql_dynamo_test
